### ISSUE TITLE
What is the purpose of the `postcode_required` field?

### ISSUE THREAD

**Issue by oliverpool** [Blagomir/mysql-country-list#4]
Hi,

first of all, thank you for this great list!

I wondered what was the purpose of the `postcode_required` field? It is set to `1` only for
```sql
(223, 'United Kingdom', 'GB', 'GBR', 44, 1, 1),
```

Could it be removed?

**Comment by Blagomir** [comment]
Hello @oliverpool,

Thanks for your pull requests and questions :-)

The initial idea of the field was "is the postcode required when you are trying to ship a parcel to this country". As in UK you can not ship anything if you don't show the postcode, but i know for many other countries postcode is not required, just full address (building, street, city).

**Comment by oliverpool** [comment]
Ok,  allright
